version: 2
jobs:
  build:
    machine:
        enabled: true
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Execute Deployment Script
          command: |
             ssh -o "StrictHostKeyChecking no" circleci@52.31.45.193 -L 5601:localhost:5601 -fN
      
      
      - run:
          name: Kibana test
          command: curl localhost:5601
