version: 2
jobs:
  build:
    machine:
        enabled: true
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Execute Deployment Script
          command: |
             ssh -o "StrictHostKeyChecking no" circleci@52.31.45.193 -L 5601:localhost:5601 -fN
      
      
      - run:
          name: Kibana test
          command: curl localhost:5601

      - run:
          name: rsync
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              rsync -avce ssh .bashrc circleci@52.31.45.193:~/test/
            else
              echo "Not master branch, dry run only"
            fi
